check for external chaincode cert instead of using helm hooks
Signed-off-by: Johann Westphall <johannwestphall@gmail.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-external-chaincode-install/templates/install_external_chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-external-chaincode-install/templates/install_external_chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-external-chaincode-install/templates/install_external_chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-external-chaincode-install/templates/install_external_chaincode.yaml
@@ -104,6 +104,11 @@ spec:
           if [ "${CHAINCODE_TLS_DISABLED}" == "false" ]; then
             echo "Getting chaincode certificates from Vault."
             vaultBevelFunc "readJson" "${VAULT_CHAINCODE_PEER_SECRET_PREFIX}/peers-${CHAINCODE_NAME}-tls"
+
+            if [ "$SECRETS_AVAILABLE" != "yes" ]; then
+                echo "Peer-Chaincode TLS certificates not found in ${VAULT_CHAINCODE_PEER_SECRET_PREFIX}/peers-${CHAINCODE_NAME}-tls"
+                exit 1
+            fi
     
             CACERT=$(echo ${VAULT_SECRET} | jq -r '.["ca_crt"]')
             CLIENT_CERT=$(echo ${VAULT_SECRET} | jq -r '.["client_crt"]')
@@ -191,7 +196,6 @@ spec:
 
           PACKAGE_NAME=${CHAINCODE_NAME}_${CHAINCODE_VERSION}
 
-          # TODO: johann: test the tls case later
           if [ "${CHAINCODE_TLS_DISABLED}" == "false" ]; then
             echo "Packaging external chaincode. TLS enabled."
             CA_CERT="$(cat ${CHAINCODE_SECRET_MOUNT_PATH}/ca.crt)"
diff --git a/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml b/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml
@@ -92,6 +92,11 @@ spec:
           if [ "${CHAINCODE_TLS_DISABLED}" == "false" ]; then
             echo "Getting chaincode certificates from Vault using key ${VAULT_CHAINCODE_SECRET}"
             vaultBevelFunc "readJson" "${VAULT_CHAINCODE_SECRET}"
+
+            if [ "$SECRETS_AVAILABLE" != "yes" ]; then
+                echo "Chaincode TLS files not found in ${VAULT_CHAINCODE_SECRET}"
+                exit 1
+            fi
             
             CACERT=$(echo ${VAULT_SECRET} | jq -r '.["ca_crt"]')
             CLIENT_CERT=$(echo ${VAULT_SECRET} | jq -r '.["client_crt"]')
